new_ses_trigger = {
    "ticket_request": "1729692036781",
    "message": "The request has been accepted and is being processed."
}
ses_result_completed = {
    "results": [
        {
            "region_id": "NORD",
            "site_id": "NORD_1",
            "cluster_id": "cluster_1",
            "server_id": "server_sud_1_2"
        }
    ],
    "processing_status": "COMPLETED-ACKNOWLEDGED",
    "ticket_request": "1729692036781"
}
ses_result_on_going = {
    "processing_status": "ON-GOING",
    "ticket_request": "1729692036781"
}

elo_result = {
    "elo_analysis_outcome": {
        "server_id": "server_sud_1_1",
        "ip_address": "192.100.010.010",
        "app_mean_deployment_time_seconds": 120
    }
}

inventory = {
    "inventory_timestamp": "2024-10-23 16:00:35.708597",
    "list_of_server": [
        {
            "server_id": "server_nord_1_1",
            "HW_list": {
                "CPU_equipped": 4,
                "cost_per_CPU": 3,
                "Disk_capacity_MB": 256000,
                "cost_Disk_per_MB": 6,
                "GPU_equipped": 0,
                "cost_GPU_per_MB": 50,
                "RAM_capacity_MB": 16000,
                "cost_RAM_per_MB": 9
            },
            "region_id": "NORD",
            "site_id": "NORD_1",
            "coordinates": {
                "latitude": 45.5,
                "longitude": 7.67
            },
            "green_power_percentage": 80,
            "CO2_emission": 20,
            "last_inventory_get_timestamp": "2024-10-21 17:00:00",
            "cluster_list": [
                {
                    "cluster_id": "cl1"
                },
                {
                    "cluster_id": "cl2"
                }
            ]
        }
    ]
}

monitoring = {
    "kpi_report_timestamp": "2024-10-23 16:10:48.258234",
    "server_list": [
        {
            "server_id": "server_nord_1_1",
            "list_of_measurement": [
                {
                    "measure_timestamp": "2024-10-21 17:00:00",
                    "energy_consumption_KwH": 900,
                    "disk_usage_%": 50,
                    "gpu_usage_%": 1,
                    "ram_usage_%": 30,
                    "cpu_usage_%": 30
                }
            ]
        }
    ]
}
nef_response = {
    "gnodeb_code": "NAB5678",
    "tracking_area": "5200",
    "antenna_lat": 40.8616,
    "antenna_lon": 14.2279
}
netbox_response = {"data": {"device_list": [
    {"name": "to-lab-edge1-server1",
     "site": {"latitude": "45.112631", "longitude": "7.670521",
              "slug": "toLabEdge1", "region": {"slug": "north"}},
     "tenant": {"slug": "t1"}, "cluster": {"name": "to-lab-edge1-cluster0"},
     "last_updated": "2024-12-05T11:09:44.487634+00:00", "modules": [
        {"display": "CPU 1: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (510)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "CPU 2: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (511)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A1: DDR4 DIMM (512)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A2: DDR4 DIMM (513)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A3: DDR4 DIMM (514)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A4: DDR4 DIMM (515)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A5: DDR4 DIMM (516)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A6: DDR4 DIMM (517)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B1: DDR4 DIMM (518)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B2: DDR4 DIMM (519)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B3: DDR4 DIMM (520)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B4: DDR4 DIMM (521)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B5: DDR4 DIMM (522)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B6: DDR4 DIMM (523)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "Disk Bay 0: AL15SEB120NY (524)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 1: AL15SEB120NY (525)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 2: MTFDDAK1T9TDN (526)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 1788}},
        {"display": "Disk Bay 3: MTFDDAK1T9TDN (527)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 1788}},
        {"display": "GPU 1: NVIDIA L40S (894)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 48, "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "PCIe-Gen3 1: Intel(R) Ethernet 25G 2P E810-XXV Adapter (528)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "PCIe-Gen3 2: Intel(R) Ethernet 25G 2P XXV710 Adapter (529)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "PCI Integrated NIC 1: Intel(R) Ethernet 10G 4P X710/I350 rNDC (530)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0, "disk_capacity_GB": 0}}],
     "powerports": [{"custom_fields": {"GreenPowerPercentage": 0}},
                    {"custom_fields": {"GreenPowerPercentage": 0}}]},
    {"name": "to-lab-edge1-server2",
     "site": {"latitude": "45.112631", "longitude": "7.670521",
              "slug": "toLabEdge1", "region": {"slug": "north"}},
     "tenant": {"slug": "t1"}, "cluster": {"name": "to-lab-edge1-cluster0"},
     "last_updated": "2024-12-05T11:09:21.457397+00:00", "modules": [
        {"display": "CPU 1: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (531)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "CPU 2: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (532)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A1: DDR4 DIMM (533)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A2: DDR4 DIMM (534)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A3: DDR4 DIMM (535)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A4: DDR4 DIMM (536)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A5: DDR4 DIMM (537)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A6: DDR4 DIMM (538)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B1: DDR4 DIMM (539)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B2: DDR4 DIMM (540)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B3: DDR4 DIMM (541)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B4: DDR4 DIMM (542)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B5: DDR4 DIMM (543)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B6: DDR4 DIMM (544)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "Disk Bay 0: AL15SEB120NY (545)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 1: AL15SEB120NY (546)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 2: MTFDDAK1T9TDN (547)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "Disk Bay 3: MTFDDAK1T9TDN (548)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "GPU 1: NVIDIA L40S (895)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 48,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 1: Intel(R) Ethernet 25G 2P E810-XXV Adapter (549)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 2: Intel(R) Ethernet 25G 2P E810-XXV Adapter (550)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCI Integrated NIC 1: Intel(R) Ethernet 10G 4P X710/I350 rNDC (551)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}],
     "powerports": [{"custom_fields": {"GreenPowerPercentage": 0}},
                    {"custom_fields": {"GreenPowerPercentage": 0}}]},
    {"name": "to-lab-edge2-server1",
     "site": {"latitude": "45.112631", "longitude": "7.670521",
              "slug": "toLabEdge2", "region": {"slug": "north"}},
     "tenant": {"slug": "t1"}, "cluster": {"name": "to-lab-edge2-cluster0"},
     "last_updated": "2024-12-05T11:09:03.932135+00:00", "modules": [
        {"display": "CPU 1: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (447)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "CPU 2: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (448)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A1: DDR4 DIMM (449)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A2: DDR4 DIMM (450)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A3: DDR4 DIMM (451)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A4: DDR4 DIMM (452)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A5: DDR4 DIMM (453)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A6: DDR4 DIMM (454)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B1: DDR4 DIMM (455)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B2: DDR4 DIMM (456)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B3: DDR4 DIMM (457)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B4: DDR4 DIMM (458)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B5: DDR4 DIMM (459)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B6: DDR4 DIMM (460)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "Disk Bay 0: AL15SEB120NY (461)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 1: AL15SEB120NY (462)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 2: KRM5XRUG960G (463)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 893}},
        {"display": "Disk Bay 3: KRM5XRUG960G (464)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 893}},
        {"display": "GPU 1: NVIDIA L40S (891)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 48,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 1: Intel(R) Ethernet 25G 2P XXV710 Adapter (465)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 2: Intel(R) Ethernet 25G 2P XXV710 Adapter (466)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCI Integrated NIC 1: Intel(R) Ethernet 10G 4P X710/I350 rNDC (467)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}],
     "powerports": [{"custom_fields": {"GreenPowerPercentage": 50}},
                    {"custom_fields": {"GreenPowerPercentage": 50}}]},
    {"name": "to-lab-edge2-server2",
     "site": {"latitude": "45.112631", "longitude": "7.670521",
              "slug": "toLabEdge2", "region": {"slug": "north"}},
     "tenant": {"slug": "t1"}, "cluster": {"name": "to-lab-edge2-cluster0"},
     "last_updated": "2024-12-05T11:08:46.732833+00:00", "modules": [
        {"display": "CPU 1: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (468)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "CPU 2: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (469)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A1: DDR4 DIMM (470)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A2: DDR4 DIMM (471)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A3: DDR4 DIMM (472)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A4: DDR4 DIMM (473)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A5: DDR4 DIMM (474)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A6: DDR4 DIMM (475)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B1: DDR4 DIMM (476)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B2: DDR4 DIMM (477)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B3: DDR4 DIMM (478)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B4: DDR4 DIMM (479)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B5: DDR4 DIMM (480)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B6: DDR4 DIMM (481)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "Disk Bay 0: AL15SEB120NY (482)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 1: AL15SEB120NY (483)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 2: MTFDDAK1T9TDN (484)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "Disk Bay 3: MTFDDAK1T9TDN (485)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "GPU 1: NVIDIA L40S (892)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 48,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 1: Intel(R) Ethernet 25G 2P XXV710 Adapter (486)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 2: Intel(R) Ethernet 25G 2P XXV710 Adapter (487)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCI Integrated NIC 1: Intel(R) Ethernet 10G 4P X710/I350 rNDC (488)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}],
     "powerports": [{"custom_fields": {"GreenPowerPercentage": 0}},
                    {"custom_fields": {"GreenPowerPercentage": 0}}]},
    {"name": "to-lab-edge2-server3",
     "site": {"latitude": "45.112631", "longitude": "7.670521",
              "slug": "toLabEdge2", "region": {"slug": "north"}},
     "tenant": {"slug": "t1"}, "cluster": {"name": "to-lab-edge2-cluster0"},
     "last_updated": "2024-12-05T11:08:16.672340+00:00", "modules": [
        {"display": "CPU 1: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (489)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "CPU 2: Intel(R) Xeon(R) Gold 6252N CPU @ 2.30GHz (490)",
         "custom_fields": {"cores": 24, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A1: DDR4 DIMM (491)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A2: DDR4 DIMM (492)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A3: DDR4 DIMM (493)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A4: DDR4 DIMM (494)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A5: DDR4 DIMM (495)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A6: DDR4 DIMM (496)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B1: DDR4 DIMM (497)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B2: DDR4 DIMM (498)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B3: DDR4 DIMM (499)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B4: DDR4 DIMM (500)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B5: DDR4 DIMM (501)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B6: DDR4 DIMM (502)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "Disk Bay 0: AL15SEB120NY (503)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 1: AL15SEB120NY (504)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1117}},
        {"display": "Disk Bay 2: MTFDDAK1T9TDN (505)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "Disk Bay 3: MTFDDAK1T9TDN (506)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "GPU 1: NVIDIA L40S (893)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 48,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 1: Intel(R) Ethernet 25G 2P XXV710 Adapter (507)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCIe-Gen3 2: Intel(R) Ethernet 25G 2P XXV710 Adapter (508)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCI Integrated NIC 1: Intel(R) Ethernet 10G 4P X710/I350 rNDC (509)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}],
     "powerports": [{"custom_fields": {"GreenPowerPercentage": 0}},
                    {"custom_fields": {"GreenPowerPercentage": 0}}]},
    {"name": "to-lab-edge3-server1",
     "site": {"latitude": "45.112631", "longitude": "7.670521",
              "slug": "toLabEdge3", "region": {"slug": "north"}},
     "tenant": {"slug": "t1"}, "cluster": {"name": "to-lab-edge3-cluster0"},
     "last_updated": "2024-12-05T11:07:52.817472+00:00", "modules": [
        {"display": "CPU 1: Intel(R) Xeon(R) Gold 5220 CPU @ 2.20GHz (573)",
         "custom_fields": {"cores": 18, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "CPU 2: Intel(R) Xeon(R) Gold 5220 CPU @ 2.20GHz (574)",
         "custom_fields": {"cores": 18, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A1: DDR4 DIMM (575)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A2: DDR4 DIMM (576)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT A3: DDR4 DIMM (577)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B1: DDR4 DIMM (578)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B2: DDR4 DIMM (579)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "DIMM SLOT B3: DDR4 DIMM (580)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                           "ram_capacity_GB": 32, "disk_capacity_GB": 0}},
        {"display": "Disk Bay 0: SSDSC2KG019T8R (581)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "Disk Bay 3: HFS1T9G32FEH-BA1 (582)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 1788}},
        {"display": "Disk Bay 6: AL15SEB24EQY (583)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 2400}},
        {"display": "Disk Bay 7: AL15SEB24EQY (584)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 0, "ram_capacity_GB": 0,
                           "disk_capacity_GB": 2400}},
        {"display": "GPU 1: NVIDIA L40S (889)",
         "custom_fields": {"cores": 0, "gpu_memory_GB": 48,
                           "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "NUMA 0 - PCIe slot 1 - FH: QLogic 10GE 2P QL41112HxCU-DE Adapter (585)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "NUMA 1 - PCIe slot 5 - FH: QLogic 10GE 2P QL41112HxCU-DE Adapter (586)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}, {
            "display": "PCI Integrated NIC 1: Intel(R) Ethernet 10G 4P X710/I350 rNDC (587)",
            "custom_fields": {"cores": 0, "gpu_memory_GB": 0,
                              "ram_capacity_GB": 0, "disk_capacity_GB": 0}}],
     "powerports": [{"custom_fields": {"GreenPowerPercentage": 0}},
                    {"custom_fields": {"GreenPowerPercentage": 0}}]}]}}
tim_monitoring_response = {"kpi_report_timestamp": "2024-12-13T12:22:57.860261005Z", "server_list": [
    {"server_id": "to-lab-edge2-server1", "list_of_measurement": [
        {"measure_timestamp": "2024-12-13T11:37:55.305961275Z", "carbon_fp_KwH": 6.137165e-8, "disk_usage_%": 3.0352418,
         "gpu_usage_%": -1, "ram_usage_%": 2.3724663, "cpu_usage_%": 1.0449765},
        {"measure_timestamp": "2024-12-13T11:52:55.305951452Z", "carbon_fp_KwH": 6.11887e-8, "disk_usage_%": 3.0356896,
         "gpu_usage_%": -1, "ram_usage_%": 2.368694, "cpu_usage_%": 1.0649953},
        {"measure_timestamp": "2024-12-13T12:07:55.305941046Z", "carbon_fp_KwH": 6.152874e-8, "disk_usage_%": 3.0357113,
         "gpu_usage_%": -1, "ram_usage_%": 2.3774078, "cpu_usage_%": 1.0692593},
        {"measure_timestamp": "2024-12-13T12:22:55.305914228Z", "carbon_fp_KwH": 6.111111e-8, "disk_usage_%": 3.035716,
         "gpu_usage_%": -1, "ram_usage_%": 2.362889, "cpu_usage_%": 1.0391829}]}, {"server_id": "to-lab-edge2-server2",
                                                                                   "list_of_measurement": [{
                                                                                       "measure_timestamp": "2024-12-13T11:37:55.305961275Z",
                                                                                       "carbon_fp_KwH": 6.162261e-8,
                                                                                       "disk_usage_%": 1.6053041,
                                                                                       "gpu_usage_%": -1,
                                                                                       "ram_usage_%": 3.2854986,
                                                                                       "cpu_usage_%": 1.8311967},
                                                                                       {
                                                                                           "measure_timestamp": "2024-12-13T11:52:55.305951452Z",
                                                                                           "carbon_fp_KwH": 6.116092e-8,
                                                                                           "disk_usage_%": 1.6053295,
                                                                                           "gpu_usage_%": -1,
                                                                                           "ram_usage_%": 3.2890453,
                                                                                           "cpu_usage_%": 1.8154507},
                                                                                       {
                                                                                           "measure_timestamp": "2024-12-13T12:07:55.305941046Z",
                                                                                           "carbon_fp_KwH": 6.111111e-8,
                                                                                           "disk_usage_%": 1.6053582,
                                                                                           "gpu_usage_%": -1,
                                                                                           "ram_usage_%": 3.2982275,
                                                                                           "cpu_usage_%": 1.8732922},
                                                                                       {
                                                                                           "measure_timestamp": "2024-12-13T12:22:55.305914228Z",
                                                                                           "carbon_fp_KwH": 6.124839e-8,
                                                                                           "disk_usage_%": 1.605398,
                                                                                           "gpu_usage_%": -1,
                                                                                           "ram_usage_%": 3.2934406,
                                                                                           "cpu_usage_%": 1.8315474}]},
    {"server_id": "test-t3-1", "list_of_measurement": [
        {"measure_timestamp": "2024-12-13T11:37:55.305961275Z", "carbon_fp_KwH": 1.1952108e-7,
         "disk_usage_%": 1.0807155, "gpu_usage_%": -1, "ram_usage_%": 3.2384229, "cpu_usage_%": 2.1770992},
        {"measure_timestamp": "2024-12-13T11:52:55.305951452Z", "carbon_fp_KwH": 9.3287355e-8,
         "disk_usage_%": 1.0807927, "gpu_usage_%": -1, "ram_usage_%": 3.2269762, "cpu_usage_%": 2.183104},
        {"measure_timestamp": "2024-12-13T12:07:55.305941046Z", "carbon_fp_KwH": 7.981801e-8, "disk_usage_%": 1.0810869,
         "gpu_usage_%": -1, "ram_usage_%": 3.2367184, "cpu_usage_%": 2.1706867},
        {"measure_timestamp": "2024-12-13T12:22:55.305914228Z", "carbon_fp_KwH": 7.3034485e-8,
         "disk_usage_%": 1.0812325, "gpu_usage_%": -1, "ram_usage_%": 3.2392561, "cpu_usage_%": 2.154746}]},
    {"server_id": "to-lab-edge1-server1", "list_of_measurement": [
        {"measure_timestamp": "2024-12-13T11:37:55.305961275Z", "carbon_fp_KwH": 6.1176245e-8,
         "disk_usage_%": 1.0187708, "gpu_usage_%": -1, "ram_usage_%": 3.4536266, "cpu_usage_%": 1.3036226},
        {"measure_timestamp": "2024-12-13T11:52:55.305951452Z", "carbon_fp_KwH": 6.128065e-8, "disk_usage_%": 1.0189838,
         "gpu_usage_%": -1, "ram_usage_%": 3.4649255, "cpu_usage_%": 1.311721},
        {"measure_timestamp": "2024-12-13T12:07:55.305941046Z", "carbon_fp_KwH": 6.111111e-8, "disk_usage_%": 1.0194643,
         "gpu_usage_%": -1, "ram_usage_%": 3.4655557, "cpu_usage_%": 1.3145473},
        {"measure_timestamp": "2024-12-13T12:22:55.305914228Z", "carbon_fp_KwH": 6.1121646e-8,
         "disk_usage_%": 1.0196608, "gpu_usage_%": -1, "ram_usage_%": 3.4638436, "cpu_usage_%": 1.3090448}]},
    {"server_id": "to-lab-edge1-server2", "list_of_measurement": [
        {"measure_timestamp": "2024-12-13T11:37:55.305961275Z", "carbon_fp_KwH": 6.13841e-8, "disk_usage_%": 0.5165577,
         "gpu_usage_%": -1, "ram_usage_%": 4.464215, "cpu_usage_%": 0.96556056},
        {"measure_timestamp": "2024-12-13T11:52:55.305951452Z", "carbon_fp_KwH": 6.1225094e-8,
         "disk_usage_%": 0.51657647, "gpu_usage_%": -1, "ram_usage_%": 4.457395, "cpu_usage_%": 0.9777336},
        {"measure_timestamp": "2024-12-13T12:07:55.305941046Z", "carbon_fp_KwH": 6.111111e-8,
         "disk_usage_%": 0.51658845, "gpu_usage_%": -1, "ram_usage_%": 4.4700375, "cpu_usage_%": 1.0256776},
        {"measure_timestamp": "2024-12-13T12:22:55.305914228Z", "carbon_fp_KwH": 6.111111e-8, "disk_usage_%": 0.5166049,
         "gpu_usage_%": -1, "ram_usage_%": 4.464882, "cpu_usage_%": 0.99095374}]}, {"server_id": "to-lab-edge2-server3",
                                                                                    "list_of_measurement": [{
                                                                                        "measure_timestamp": "2024-12-13T11:37:55.305961275Z",
                                                                                        "carbon_fp_KwH": 6.1121646e-8,
                                                                                        "disk_usage_%": 1.5783789,
                                                                                        "gpu_usage_%": -1,
                                                                                        "ram_usage_%": 2.4941869,
                                                                                        "cpu_usage_%": 1.292351},
                                                                                        {
                                                                                            "measure_timestamp": "2024-12-13T11:52:55.305951452Z",
                                                                                            "carbon_fp_KwH": 6.1454024e-8,
                                                                                            "disk_usage_%": 1.57839,
                                                                                            "gpu_usage_%": -1,
                                                                                            "ram_usage_%": 2.4937742,
                                                                                            "cpu_usage_%": 1.2995584},
                                                                                        {
                                                                                            "measure_timestamp": "2024-12-13T12:07:55.305941046Z",
                                                                                            "carbon_fp_KwH": 6.1358236e-8,
                                                                                            "disk_usage_%": 1.5784045,
                                                                                            "gpu_usage_%": -1,
                                                                                            "ram_usage_%": 2.5018826,
                                                                                            "cpu_usage_%": 1.3001057},
                                                                                        {
                                                                                            "measure_timestamp": "2024-12-13T12:22:55.305914228Z",
                                                                                            "carbon_fp_KwH": 6.1366855e-8,
                                                                                            "disk_usage_%": 1.5784204,
                                                                                            "gpu_usage_%": -1,
                                                                                            "ram_usage_%": 2.4962373,
                                                                                            "cpu_usage_%": 1.3011456}]}]}
tim_orchestrator_response = {"app_mean_deployment_time_seconds": 20, "list_of_images": [
    {"server_id": "to-lab-edge2-server1", "indirizzo_ip": "163.162.13.196", "DNS": "163.162.13.196.nip.io"},
    {"server_id": "to-lab-edge2-server2", "indirizzo_ip": "163.162.13.197", "DNS": "163.162.13.197.nip.io"},
    {"server_id": "to-lab-edge2-server3", "indirizzo_ip": "163.162.13.198", "DNS": "163.162.13.198.nip.io"}]}
